Strongly Recommend to Read and Understand the followings <br>
Python tutorials, Numpy tutorial, and Pandas tutorial <br>
from https://www.w3schools.com/python/default.asp <br>

Part 2. <br>
Indentation Grammer
<br>
<br>
In Python, grammer blcok is distingusihed by indentation,
Python standard suggests to use Tab key (as 4 spaces) for indentation

In [ ]:
# Indentation in Loop

for i in range(10): # Loop starts
    print("Hello World!") # "print(i)" is with indentation, so it belongs to for loop

print("Loop Ends") # Since this line has no indentation, it is not in the loop

In [ ]:
# Indentation in Loop
# Case of nested loop

for i in range(3): # Loop1 starts
    # for every Loop1, below code will be executed
    print("Loop1", i)
    tmp_list = []
    for j in range(3): # Loop 2 starts, since this is in Loop1, Loop2 will be repeated 3 times
        # For every Loop2, below code will be executed
        tmp_list.append(i*j)

    print(tmp_list) # This code is in Loop1 only.

print("Loop Ends") # Since this line has no indentation, it is not in both Loop1 and Loop2.

Part 2. <br>
Function
<br>
<br>
Function has a predefined code, a set of instructions

In Python we can define a function using "def"
You can use other functions inside of a funcion

<br>
def hello_world_printer():
<br>
&emsp; print("Hello World") # tab indentation

In [ ]:
def hello_world_printer():
    print("Hello World")

hello_world_printer() # Calling a function, function()

Parameters(arguments) are inputs of a function <br>
<br>
def string_printer(mystring):
<br>
&emsp; print(mystring)
<br>
<br>
In this example function,
I set parameter "mystring"
<br>
<br>
string_printer("Hello") # calling a function with argument "Hello"
<br>
<br>

More precisely,<br>
Parameter is the variable in the declaration of the function <br>
Argument is the actual value of this variable that gets passed to the function

In [ ]:
# Function with parameter
def string_printer(mystring):
    print(mystring)

string_printer() # This raises an error

In [ ]:
string_printer("Hello") # With an argument, it works well

In [ ]:
# Function with multiple parameters

def big_or_small(a, b):
    if a > b:
        print(f"a:{a} is bigger than b:{b}")
    elif a < b:
        print(f"a:{a} is smaller than b:{b}")
    else:
        print(f"a:{a} and b:{b} are equal")

In [ ]:
big_or_small(1) # If I give only one argument, it raises an error

In [ ]:
big_or_small(10, 5)

In [ ]:
# Type of parameter for a function is not limited
# Even a function an be an arugment

def hello_printer():
    print("Hello")

def world_printer():
    print("World")

def function_caller(other_function):
    print("function start")
    other_function()
    print("function end")

In [ ]:
type(hello_printer)

In [ ]:
type(hello_printer())

In [ ]:
function_caller(hello_printer)

In [ ]:
function_caller(world_printer)

In [ ]:
# Function return

def calculate_addtion(a,b):
    result = a+b
    return result

In [ ]:
type(calculate_addtion)

In [ ]:
type(calculate_addtion(10,5))

In [ ]:
print(calculate_addtion(10,5))

Part 2 <br>
Package/Library

Some people already creates some useful objects and functions <br>
Most of them are open-source, which means that we can access their source code and use it freely
<br>
<br>
There are some famous ones like
* Numpy
* Pandas
* Matplotlib
* etc...



In [ ]:
# In Colab, you can install packages by
# !pip install "package name"
!pip install numpy

In [ ]:
# We can use packages using "import"
import numpy

In [ ]:
numpy.__version__

In [ ]:
# For convenience, some popular packages are imported as conventional shortname
# numpy as np, pandas as pd, matplotlib.pyplot as plt
import numpy as np

In [ ]:
np.__version__

In [ ]:
# To master a library, reading project documentation is the best
# Here is the official document for Numpy
# "https://numpy.org/doc/1.25/user/index.html#user"

Numpy

In [ ]:
# Numpy is for mathematical calculations
# It is fast and efficient than pure Python
import numpy as np

In [ ]:
# Most numpy features are related with a numpy object called numpy.ndarray
# Think it as a vector in linear algebra
np_arr1 = np.array([1,2,3,4,5])
np_arr2 = np.array([1,2,3,4,5])

In [ ]:
print(type(np_arr1))
print(np_arr1)
print(np_arr1[0])
print(np_arr1[-1])

In [ ]:
[1,2,3] + [1,2,3,4,5]

In [ ]:
np_arr1 + np_arr2

In [ ]:
np.array([1,2,3]) + np.array([1,2,3,4,5])

In [ ]:
np_arr1 * np_arr2

In [ ]:
np.dot(np_arr1, np_arr2)

In [ ]:
np_arr1 @ np_arr2

In [ ]:
# Creating 3 by 3 matrix
np_mat = np.array(
    [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
)

np_arr = np.array([1,1,1])
np_arr_v = np.array([[1],[1],[1]])

In [ ]:
np_mat @ np_arr

In [ ]:
np.dot(np_mat, np_arr)

In [ ]:
# 2 by 3 matrix
np_mat = np.array(
    [
    [4,5,6],
    [7,8,9]]
)

np_arr = np.array([1,1,1])

In [ ]:
np_mat.shape

In [ ]:
np_arr @ np_mat

In [ ]:
np.dot(np_arr, np_mat)

In [ ]:
np.dot(np_mat, np_arr)

In [ ]:
np_mat

In [ ]:
# Transpose
np_mat.transpose()

In [ ]:
# Transpose
np_mat.T

In [ ]:
# Calculating some statistics
np_arr = np.array([1,2,3,4,5,6,7,9,10])
print("mean", np.mean(np_arr))
print("std", np.std(np_arr))

In [ ]:
# Reshape
np_arr = np.array([1,2,3,4,5,6,7,8,9])
np_mat = np_arr.reshape((3,3))
np_mat

In [ ]:
# Reshape
np_arr = np.array([1,2,3,4,5,6])
np_mat = np_arr.reshape((2,-1))
np_mat

In [ ]:
# 2 by 2 matrix
np_mat = np.array([[1,2],[3,4]])
print(np_mat)
# Indexing is arr[row][col]
print(np_mat[0][1])
print(np_mat[1][1])

In [ ]:
# Masking with np.where

np_arr = np.array([1,2,3,4,5])

print(np.where(np_arr>=3)) # np.where function returns indices of where the given condition is True
# Using this we can access on an array where the condtion is met
print(np_arr[np.where(np_arr>=3)])

Pandas

In [ ]:
# pandas is for handling data
# If your are R user, it is same as R dataframe
# pandas has pandas.DataFrame

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

Connect to your Google Drive
<br>
<br>
To access on files in your google drive, we have to connect the colab noteboox to your dirve

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# pd.read_csv()
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Risk_n_PM/crsp-2.csv") # /content/drive/MyDrive/Colab Notebooks/YOUR OWN LOCATION/

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
df.head(5)

In [ ]:
df.tail(5)

In [ ]:
df["date"]

In [ ]:
df[["date","ret"]]

In [ ]:
df

In [ ]:
# DataFrame indexing - using ".loc"

df.loc[0, "date"] # df.loc[index_name, column_name]

In [ ]:
df.loc[[0,1,2], "date"]

In [ ]:
# DataFrame indexing - using ".iloc"
df.iloc[0,2]

In [ ]:
df.iloc[0, 0:4]

In [ ]:
df["permno"] * 2

In [ ]:
df["permno"] + df["permno"]

In [ ]:
df.values

In [ ]:
# DataFrame Masking
df[df["permno"] >= 50000]

# df["permno"] >= 50000 -> returns indices where given condition is met

In [ ]:
# Statistics with DataFrame
print("mean", df["ret"].mean())
print("std", df["ret"].std())
print("skew", df["ret"].skew())
print("kurt", df["ret"].kurt())

In [ ]:
# checking data type
df.dtypes

In [ ]:
df

In [ ]:
# Convert date into pd.datetime data type
df["date"] = pd.to_datetime(df["date"])
df.dtypes

In [ ]:
df

In [ ]:
df["ret"].plot()

In [ ]:
df

In [ ]:
# Pivot
df_ret = pd.pivot_table(df, "ret", "date", columns="permno")

In [ ]:
df_ret

Matplotlib.pyplot

In [ ]:
# matplotlib is a drawing tool

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
target_ret = df_ret[10104]

plt.figure()
plt.plot(df_ret.index, target_ret)
plt.show()

In [ ]:
plt.figure()
plt.scatter(df_ret.index, target_ret)
plt.show()

In [ ]:
plt.figure()
plt.scatter(df_ret.index, df_ret[10104])
plt.scatter(df_ret.index, df_ret[10107])
plt.show()

In [ ]:
plt.figure()
plt.scatter(df_ret.index, df_ret[10104], label=10104)
plt.scatter(df_ret.index, df_ret[10107], label=10107)
plt.legend()
plt.show()

In [ ]:
plt.figure()
plt.scatter(df_ret.index, df_ret[10104], label="scatter")
plt.plot(df_ret.index, df_ret[10104], label="line")
plt.legend()
plt.show()

In [ ]:
plt.figure()
plt.scatter(df_ret.index, df_ret[10104], label="scatter")
plt.plot(df_ret.index, df_ret[10104], label="line", c="skyblue", alpha=0.7)
plt.legend()
plt.show()

In [ ]:
plt.figure()
plt.hist(df_ret[10104])
plt.show()

In [ ]:
plt.figure()
plt.hist(df_ret[10104], bins=100)
plt.show()

In [ ]:
# Practice Problems

# P1)
# Create a function that takes a interger as an input
# if the interger is a prime number, it prints "prime"
# otherwise, it returns a list filled with factors of the input integer

# P2)
# Create 3 by 3 matrix 'A' with numbers 1 ~ 9
# Make it as upper triangular matrix (use matrix indexing to change value mat[1][p] = 0)
# (Matrix Mulplication) multiply A and A transpose

# P3)
# Pick any stock,
# Draw the followings together
# a scatter plot of stock returns
# a constant line, value of constant is average return
# two more constant line, one is (average return + 1.96 * standard deviation of returns), and the other is (average return - 1.96 * standard deviation of returns)

In [1]:
def detect_prime(integer):
  factors = []

  for factor_candidate in range(1,integer+1):
    if integer % factor_candidate == 0:
      factors.append(factor_candidate)
  

  if len(factors) == 2:
    print("prime")
  else:
    return factors

In [2]:
detect_prime(7)

prime


In [4]:
import numpy as np

In [6]:
li  = [i for i in range(1,10)]
A = np.array([li])
A

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
A = A.reshape(3,-1)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
A[1][0] = 0
A[2][0] = 0
A[2][1] = 0
A

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [11]:
np.dot(A, A.T)

array([[14, 28, 27],
       [28, 61, 54],
       [27, 54, 81]])